version: '3.8'

x-client-common: 
  &client-common
  build: . 
  depends_on: 
    - server
  command: "distributed_learning.fedadapt_client_run"
  volumes:
    - ./data:/usr/src/app/data
    - ./results:/usr/src/app/results
  networks: 
    - fedadapt_network

services: 

  server: 
    container_name: fedadapt_server
    build: . 
    command: "distributed_learning.fedadapt_server_run"
    networks: 
      - fedadapt_network
    volumes:
      - ./data:/usr/src/app/data
      - ./results:/usr/src/app/results


  client_pi41: 
    << : *client-common
    hostname: "pi41"

  client_pi42: 
    << : *client-common
    hostname: "pi42"

  client_jetson-desktop: 
    << : *client-common
    hostname: "jetson-desktop"

  client_pi31: 
    << : *client-common
    hostname: "pi31"

  client_pi32: 
    << : *client-common
    hostname: "pi32"


networks:
  fedadapt_network: 
    external: true

